# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sort_merge_join <- function(r, s, cpr) {
    .Call('_GenericsJoin_sort_merge_join', PACKAGE = 'GenericsJoin', r, s, cpr)
}

